name: build

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path--to-lcov: coverage.xml
